[package]
name = "game-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy = "0.15.2"
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
crossbeam = "0.8.4"
messages = { path = "../messages"}

[package.metadata.wasm-pack.profile.release]
wasm-opt = false